org: tyvdh
app: nft-stellar-buzz-serverless
service: nft-stellar-buzz-serverless
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    keepOutputDirectory: true
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
        - sodium-native
    packager: yarn
    packagerOptions:
      noInstall: true
      scripts:
        - yarn --ignore-optional

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  lambdaHashingVersion: 20201221
  environment:
    HORIZON_URL: ${env:HORIZON_URL}
    STELLAR_NETWORK: ${env:STELLAR_NETWORK}
    SIGNER_SK: ${env:SIGNER_SK}
    SPONSOR_SK: ${env:SPONSOR_SK}
  tracing:
    lambda: true
  httpApi:
    cors: true

functions:
  call:
    handler: src/call.default
    memorySize: 256
    timeout: 8
    events:
      - httpApi:
          method: POST
          path: /contract