name = "nft-stellar-buzz-wrangler"
type = "javascript"
compatibility_date = "2022-03-03"

account_id = "ba55b7ae9acfb3ed152103e3497c0752"
usage_model = "bundled"
zone_id = "f0a8062abb52ff32bd17c28172f5e10e"
route = "nft-api.stellar.buzz/*"
workers_dev = false
kv_namespaces = [ 
	{ binding = "FLAGGED", id = "cf26f4acc3104af98085fbae12be91a5" }
]

[vars]
STELLAR_NETWORK = "TESTNET"
HORIZON_URL = "https://horizon-testnet.stellar.org"
IMGIX_DOMAIN = "nft-stellar-buzz.imgix.net"
# SIGNER_SK = contract-signer-secret // upload via wrangler (https://developers.cloudflare.com/workers/cli-wrangler/commands/#put)
# SPONSOR_SK = offer-sponsor-secret // upload via wrangler
# IMGIX_TOKEN = imgix-image-signing-token // if using imgix for image caching. upload via wrangler

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./shim.mjs"